# Flow Matching Training Configuration - Pure Flow Matching System
# D2PLM Protein Language Model with Discrete Absorbing Flow Matching
# Based on arXiv:2407.15595v2 - Completely Independent from Diffusion

defaults:
  - _self_

# 1. Model Architecture Configuration
model:
  tokenizer: "facebook/esm2_t33_650M_UR50D"
  vocab_size: 33
  max_position_embeddings: 1024
  hidden_size: 512
  num_hidden_layers: 28
  num_attention_heads: 16
  intermediate_size: 2048
  time_embedding_dim: 256
  hidden_dropout_prob: 0
  attention_probs_dropout_prob: 0
  layer_norm_eps: 1e-5
  initializer_range: 0.02

# 2. Flow Matching Configuration (Core Parameters)
flow_matching:
  num_flow_steps: 200
  flow_schedule: "cosine"  # Options: 'linear', 'cosine', 'sigmoid'
  min_flow_time: 1e-5     # Minimum flow time (near clean data)
  max_flow_time: 1.0      # Maximum flow time (fully corrupted)

# 3. Dataset Configuration
data:
  train_lmdb_path: "/workspace/d2plm/prepared_dataset/train_lmdb"
  val_lmdb_path: "/workspace/d2plm/prepared_dataset/validation_lmdb"
  train_cache_dir: "/workspace/d2plm/data_cache/train"
  val_cache_dir: "/workspace/d2plm/data_cache/validation"
  max_length: 1022
  batch_size: 4 # per_device_train_batch_size for flow matching

# 4. Training Arguments Configuration
training:
  max_steps: 20
  learning_rate: 4e-4
  weight_decay: 0.01
  gradient_accumulation_steps: 32

  # Optimizer and Learning Rate Scheduler
  optim: "adamw_torch_fused"
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1

  # EMA Configuration
  ema_enabled: false  # 先关闭，专注核心功能
  ema_decay: 0.9999
  ema_update_interval: 1  # Update EMA every N steps

  # Checkpoint and Evaluation Strategy
  save_strategy: "steps"
  save_steps: 500
  logging_steps: 125
  evaluation_strategy: "steps"
  eval_steps: 500
  
  # Model Checkpoint Management
  save_total_limit: 50
  load_best_model_at_end: false
  ckpt: null # For resuming from checkpoint

# 5. System Configuration
system:
  device: "cuda"
  seed: 42
  fp16_is_avaliable: "True"
  dataloader_prefetch_factor: 20
  dataloader_num_workers: 12

# 6. Output and Logging Configuration
weight:
  output_dir: "/workspace/d2plm/weight_flow_matching"

logging:
  report_to: "wandb"
  logging_strategy: "steps"

# 7. WandB Configuration for Flow Matching
wabdb:
  project: "D2PLM_FlowMatching_Pure"
  entity: null
  run_name_prefix: "D2PLM_FM"

# 8. Checkpointing Strategy
checkpointing:
  save_strategy: "steps"