# DIT (Diffusion Transformer) Training Configuration - Flow Matching Edition
# Based on Discrete Flow Matching (arXiv:2407.15595v2)

defaults:
  - _self_

# 1. Model Configuration (Unchanged)
model:
  tokenizer: "facebook/esm2_t33_650M_UR50D"
  vocab_size: 33
  max_position_embeddings: 1024
  hidden_size: 512
  num_hidden_layers: 32
  num_attention_heads: 16
  intermediate_size: 2048
  time_embedding_dim: 256
  hidden_dropout_prob: 0
  attention_probs_dropout_prob: 0
  layer_norm_eps: 1e-5
  initializer_range: 0.02

# 2. Flow Matching Scheduler Configuration (New!)
flow_matching:
  num_flow_steps: 100
  flow_schedule: "cosine"  # Options: 'linear', 'cosine', 'sigmoid'
  min_flow_time: 1e-5
  max_flow_time: 1.0

# 3. Data Configuration (Unchanged)
data:
  train_lmdb_path: "/workspace/d2plm/prepared_dataset/train_lmdb"
  val_lmdb_path: "/workspace/d2plm/prepared_dataset/validation_lmdb"
  train_cache_dir: "/workspace/d2plm/data_cache/train"
  val_cache_dir: "/workspace/d2plm/data_cache/validation"
  max_length: 1024
  batch_size: 8 # Note: This is per_device_train_batch_size

# 4. Core Training Configuration (for TrainingArguments)
training:
  max_steps: 160000
  learning_rate: 4e-4
  weight_decay: 0.01
  gradient_accumulation_steps: 48
  
  # Optimizer and LR Scheduler
  optim: "adamw_torch_fused"
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.1

  # Saving, Logging, and Evaluation Frequency
  save_strategy: "steps"
  save_steps: 500
  logging_steps: 125
  evaluation_strategy: "steps"
  eval_steps: 500
  
  # Checkpoint Management
  save_total_limit: 50
  load_best_model_at_end: false
  ckpt: null # Retain for checkpoint resumption

# 5. System and Environment Configuration
system:
  device: "cuda"
  seed: 42
  mixed_precision: "fp16"
  dataloader_prefetch_factor: 128
  dataloader_num_workers: 23

# 6. Weight Output and Logging Configuration
weight:
  output_dir: "/workspace/d2plm/weight_flow_matching"

logging:
  report_to: "wandb"
  logging_strategy: "steps"

# WandB specific configuration
wabdb:
  project: "D2PLM_DiT_FlowMatching"
  entity: null
  run_name_prefix: "D2PLM_FM" # For dynamic run name generation

checkpointing:
  save_strategy: "steps"

# 7. CRUCIAL: Scheduler Selection (This is the key parameter!)
scheduler:
  use_flow_matching_scheduler: true  # Set to false to use traditional diffusion